### ISSUE TITLE
Fixed Building Sprite Positions

### ISSUE THREAD

**Issue by Grantelbart4** [OpenRA/ra2#225]
Hey comrade. I fixed a lot of Sprite offsets for the civilian buildings.
Here is the code for the sequences/civilian-structures.yaml file

```yaml
cafncb:
	Defaults:
		Offset: 0, -12
		UseTilesetCode: true
	idle: ctfncb
		Length: 16
		ShadowStart: 32
	damaged-idle: ctfncb
		Start: 16
		Length: 16
		ShadowStart: 48
	icon: wallicon
		Offset: 0,0
		UseTilesetCode: false

cafncw:
	Defaults:
		Offset: 0, -12
		UseTilesetCode: true
	idle: ctfncw
		Length: 16
		ShadowStart: 32
	damaged-idle: ctfncw
		Start: 16
		Length: 16
		ShadowStart: 48
	icon: wallicon
		Offset: 0,0
		UseTilesetCode: false

gasand:
	Defaults:
		Offset: 0, -12
		UseTilesetCode: true
	idle: gtsand
		Length: 16
		ShadowStart: 32
	damaged-idle: gtsand
		Start: 16
		Length: 16
		ShadowStart: 48
	icon: wallicon
		Offset: 0,0
		UseTilesetCode: false

cafncp:
	Defaults:
		Offset: 0, -12
		UseTilesetCode: true
	idle: ctfncp
		Length: 16
		ShadowStart: 32
	damaged-idle: ctfncp
		Start: 16
		Length: 16
		ShadowStart: 48
	icon: wallicon
		Offset: 0,0
		UseTilesetCode: false

cakrmw:
	Defaults:
		Offset: 0, -12
		UseTilesetCode: true
	idle: ctkrmw
		Length: 16
		ShadowStart: 32
	damaged-idle: ctkrmw
		Start: 16
		Length: 16
		ShadowStart: 48
	icon: wallicon
		Offset: 0,0
		UseTilesetCode: false

cawash01:
	idle: cgwash01
		ShadowStart: 4
		Offset: 0, -60
	damaged-idle: cgwash01
		Start: 1
		ShadowStart: 5
		Offset: 0, -60

cawash03:
	idle: cuwash03
		ShadowStart: 4
		Offset: -15, -53
	damaged-idle: cuwash03
		Start: 1
		ShadowStart: 5
		Offset: -15, -53

cawash04:
	idle: cuwash04
		ShadowStart: 4
		Offset: 0, -60
	damaged-idle: cuwash04
		Start: 1
		ShadowStart: 5
		Offset: 0, -60

cawash05:
	idle: cuwash05
		ShadowStart: 4
		Offset: -30, -45
	damaged-idle: cuwash05
		Start: 1
		ShadowStart: 5
		Offset: -30, -45

cawash06:
	idle: cuwash06
		ShadowStart: 5
		Offset: -30, -45
	damaged-idle: cuwash06
		Start: 1
		ShadowStart: 7
		Offset: -30, -45

cawash07:
	idle: cuwash07
		ShadowStart: 4
		Offset: 0, -45
	damaged-idle: cuwash07
		Start: 1
		ShadowStart: 5
		Offset: 0, -45

cawash08:
	idle: cuwash08
		ShadowStart: 4
		Offset: 0, -45
	damaged-idle: cuwash08
		Start: 1
		ShadowStart: 5
		Offset: 0, -45

cawash09:
	idle: cuwash09
		ShadowStart: 4
		Offset: 0, -45
	damaged-idle: cuwash09
		Start: 1
		ShadowStart: 5
		Offset: 0, -45

cawash10:
	idle: cuwash10
		ShadowStart: 4
		Offset: 0, -60
	damaged-idle: cuwash10
		Start: 1
		ShadowStart: 5
		Offset: 0, -60

cawash11:
	idle: cuwash11
		ShadowStart: 4
		Offset: 0, -60
	damaged-idle: cuwash11
		Start: 1
		ShadowStart: 5
		Offset: 0, -60

cawsh12:
	idle: cgwsh12
		ShadowStart: 4
		Offset: 0, -45
	damaged-idle: cgwsh12
		Start: 1
		ShadowStart: 5
		Offset: 0, -45

cawash13:
	idle: cuwash13
		ShadowStart: 4
		Offset: 15, -53
	damaged-idle: cuwash13
		Start: 1
		ShadowStart: 5
		Offset: 15, -53

cawash14:
	idle: cgwash14
		ShadowStart: 4
		Offset: 0, -45
	damaged-idle: cgwash14
		Start: 1
		ShadowStart: 5
		Offset: 0, -45

cawash15:
	idle: cgwash14
		ShadowStart: 4
		Offset: 0, -45
	damaged-idle: cgwash14
		Start: 1
		ShadowStart: 5
		Offset: 0, -45

cawash16:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

cawash17:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

cawash18:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 3

cawash19:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy01:
	idle: cunewy01
		ShadowStart: 4
		Offset: 0, -60
	damaged-idle: cunewy01
		Start: 1
		ShadowStart: 5
		Offset: 0, -60

canewy04:
	Defaults:
	idle: cgnewy04
	damaged-idle: cgnewy04
		Start: 1

canewy05:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 3

canewy06:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy07:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy08:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy10:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy11:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy12:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy13:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy14:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy15:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy16:
	Defaults:
		Offset: 0, -60
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy17:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy18:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy20:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canewy21:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

caarmy01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: -15, -38
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: -15, -38

caarmy02:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2

caarmy03:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2

caarmy04:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2

cawa2a:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -45
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -45

cawa2b:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -45
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -45

cawa2c:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -45
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -45

cawa2d:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -45
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -45

cafarm01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -30
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -30

cafarm02:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -16
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15

cafarm06:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

cafrma:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

cafrmb:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2

cabarn02:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2

causfgl:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15
	flag: causfgl_a
		Length: 16
		ShadowStart: 16
		Offset: 0, -15

carufgl:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15
	flag: carufgl_a
		Length: 16
		ShadowStart: 16
		Offset: 0, -15

cairfgl:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15
	flag: cairfgl_a
		Length: 16
		ShadowStart: 16
		Offset: 0, -15

capofgl:
	idle: capofgl
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle: capofgl
		Start: 1
		ShadowStart: 5
		Offset: 0, -15
	flag: capofgl_a
		Length: 16
		ShadowStart: 16
		Offset: 0, -15

caskfgl:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15
	flag: cuskfgl_a
		Length: 16
		ShadowStart: 16
		Offset: 0, -15

calbfgl:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15
	flag: culbfgl_a
		Length: 16
		ShadowStart: 16
		Offset: 0, -15

cafrfgl:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15
	flag: cufrfgl_a
		Length: 16
		ShadowStart: 16
		Offset: 0, -15

cagefgl:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15
	flag: cugefgl_a
		Length: 16
		ShadowStart: 16
		Offset: 0, -15

cacufgl:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15
	flag: cucufgl_a
		Length: 16
		ShadowStart: 16
		Offset: 0, -15

caukfgl:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15
	flag: cuukfgl_a
		Length: 16
		ShadowStart: 16
		Offset: 0, -15

camisc01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		ShadowStart: 4
		Offset: 0, -15

camisc02:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15

camisc03:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15

camisc04:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15

camisc05:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 2
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 3
		Offset: 0, -15

camisc06:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: -15, -22
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: -15, -22

camsc07:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: -15, -22
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: -15, -22

camsc08:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: -15, -22
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: -15, -22

camsc09:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, 0
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: -15, -22

camsc10:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -60
	damaged-idle:
		Offset: 0, -60
		Start: 1
		ShadowStart: 5

camsc11:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15

camsc12:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -15
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -15

camsc13:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 15, -22
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 15, -22

camiam01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

camiam02:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

camiam03:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

camiam04:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

camiam05:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

camiam06:
	Defaults:
		Offset: 0, -58
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

camiam07:
	Defaults:
		Offset: 0, -58
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

camiam08:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

castrt01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 3

castrt02:
	idle:
		ShadowStart: 3

castrt03:
	idle:
		ShadowStart: 3

castrt04:
	idle:
		ShadowStart: 3

castrt05:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 3

camex01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

camex02:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

camex03:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

camex04:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

camex05:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 2
		ShadowStart: 5

castl01:
	Defaults:
		UseTilesetCode: true
	idle: custl01
		ShadowStart: 4
	damaged-idle: custl01
		Start: 1
		ShadowStart: 5

castl02:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle: custl02
		ShadowStart: 4
	damaged-idle: custl02
		Start: 1
		ShadowStart: 5

castl03:
	Defaults:
		UseTilesetCode: true
	idle: custl03
		ShadowStart: 4
	damaged-idle: custl03
		Start: 1
		ShadowStart: 5

castl04:
	idle: cgstl04
		ShadowStart: 3
	damaged-idle: cgstl04
		Start: 1
		ShadowStart: 4

castl05a:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

castl05b:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

castl05c:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

castl05d:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

castl05e:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

castl05f:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

castl05g:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

castl05h:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

cacolo01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: -15, -53
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: -15, -53

caind01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -53
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -53

calab:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 15, -45
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 15, -45

cagas01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
		Offset: 0, -45
	damaged-idle:
		Start: 1
		ShadowStart: 5
		Offset: 0, -45

cahse01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 2
	damaged-idle:
		Start: 1
		ShadowStart: 4

cahse02:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 2
	damaged-idle:
		Start: 1
		ShadowStart: 4

cahse03:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 2
	damaged-idle:
		Start: 1
		ShadowStart: 4

cahse04:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 2
	damaged-idle:
		Start: 1
		ShadowStart: 4

cahse05:
	Defaults:
		UseTilesetCode: true
	idle:

cahse06:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 2
	damaged-idle:
		Start: 1
		ShadowStart: 4

cahse07:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 2
	damaged-idle:
		Start: 1
		ShadowStart: 4

cawt01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 2
	damaged-idle:
		Start: 1
		ShadowStart: 3

cabunk01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

cabunk02:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus01:
	idle: cgrus01
		ShadowStart: 4
	damaged-idle: cgrus01
		Start: 1
		ShadowStart: 5

carus02a:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus02b:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus02c:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus02d:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus02e:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus02f:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus02g:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus03:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus04:
	Defaults:
		Offset: 0, -58
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus05:
	Defaults:
		UseTilesetCode: true
		Offset: 0, -58
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus07:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus06:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus08:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus09:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus10:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

carus11:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

cachig01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

cachig02:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

cachig03:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

cachig04:
	idle: cgchig04
		ShadowStart: 4
	damaged-idle: cgchig04
		Start: 1
		ShadowStart: 5

cachig05:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

cachig06:
	idle: cgchig06
		ShadowStart: 4
	damaged-idle: cgchig06
		Start: 1
		ShadowStart: 5

catech01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

catexs01:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

catexs02:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

catexs03:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

catexs04:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

catexs05:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

catexs06:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

catexs07:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

catexs08:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canwy05:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canwy09:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canwy22:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canwy23:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canwy24:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canwy25:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

canwy26:
	Defaults:
		Offset: 0, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

camov01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 3
	damaged-idle:
		Start: 1
		ShadowStart: 4
	idle-overlay: camov01_a
		Length: 30
		Tick: 200
	damaged-idle-overlay: camov01_a
		Start: 30
		Length: 30
		Tick: 200

camov02:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5
	idle-overlay: camov02_a
		Length: 2
		Tick: 200
	damaged-idle-overlay: camov02_a
		Start: 2
		Length: 2
		Tick: 200

capars01:
	idle: cgpars01
		ShadowStart: 4
	damaged-idle: cgpars01
		Start: 1
		ShadowStart: 5

capars02:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

capars04:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

capars05:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

capars06:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

capars07:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

capars08:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

capars09:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

capars10:
	Defaults:
		UseTilesetCode: true
		Offset: 0, 0
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

capars11:
	idle: cgpars11
		Offset: 15, -54
		ShadowStart: 4
	damaged-idle: cgpars11
		Start: 1
		ShadowStart: 5

capars12:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

capars13:
	Defaults:
		Offset: -20, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

capars14:
	Defaults:
		Offset: -20, -50
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

cats01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 3
	damaged-idle:
		Start: 1
		ShadowStart: 4

cagard01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 3
	damaged-idle:
		Start: 1
		ShadowStart: 4

caeur1:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

caeur2:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

caeur04:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

caprs03:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

caswst01:
	Defaults:
		UseTilesetCode: true
	idle:
		ShadowStart: 4
	damaged-idle:
		Start: 1
		ShadowStart: 5

cacity01:
	idle:
		ShadowStart: 3

cacity02:
	idle:
		ShadowStart: 3

cacity03:
	idle:
		ShadowStart: 3

cacity04:
	idle:
		ShadowStart: 3

city01:
	idle:
		ShadowStart: 2

city02:
	idle:
		ShadowStart: 2

city03:
	idle:
		ShadowStart: 2

city04:
	idle:
		ShadowStart: 2

city05:
	idle:
		ShadowStart: 2

```
